name: new_quiz_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.6
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  build_runner: ^2.4.7
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  zoom_tap_animation: ^1.1.0
  percent_indicator: ^4.2.3
  math_keyboard: ^0.2.1
  flutter_math_fork: ^0.7.2
  flutter_slidable: ^3.0.1
  connectivity_plus: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^11.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/png/
    - assets/svg/
    - assets/translations/


  fonts:
     - family: Baloo2
       fonts:
             - asset: assets/fonts/Baloo2-Bold.ttf
             - asset: assets/fonts/Baloo2-ExtraBold.ttf
             - asset: assets/fonts/Baloo2-Medium.ttf
             - asset: assets/fonts/Baloo2-Regular.ttf
             - asset: assets/fonts/Baloo2-SemiBold.ttf